### ISSUE TITLE
Inconsistent discounting of operational and capital costs?

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS_GNU_MathProg#38]
Discounting of capital investment and operating costs using different points in the year.

@chrwm identified that equations CC2 and OC4 use different discounting factors, with OC4 adding 0.5 to the initial year. Presumably this moves the discounting to the middle of the year for operating costs (which is an assumption because variable costs may be spread unevenly over the course of year), but then combines this with capital investment costs discounted to the start of the year.

```ampl
s.t. CC2_DiscountingCapitalInvestment{r in REGION, t in TECHNOLOGY, y in YEAR}: 
    CapitalInvestment[r,t,y]/
        ((1+DiscountRate[r])^(y-min{yy in YEAR} min(yy))) 
    = 
    DiscountedCapitalInvestment[r,t,y];
```

```ampl
s.t. OC4_DiscountedOperatingCostsTotalAnnual{r in REGION, t in TECHNOLOGY, y in YEAR}: 
    OperatingCost[r,t,y]/
        ((1+DiscountRate[r])^(y-min{yy in YEAR} min(yy) + 0.5)) 
    = 
    DiscountedOperatingCost[r,t,y];
```
Should these values be consistent?

See also equations E5, SI5, SI8, SI9, SV4

**Comment by tniet** [comment]
Hi @willu47 - I think that the existing structure is correct (or at least not wildly off).  Capital costs for installing a plant occur before the plant is functional, so should happen at the start of the year, while operating costs can be averaged across the year so mid-year is a good assumption.  The capital financing costs of a multi-year plant aren't currently included in OSeMOSYS but might be a nice addition.
