### ISSUE TITLE
Check of TotalAnnualMaxCapacityInvestment and TotalAnnualMinCapacityInvestment

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/OSeMOSYS_GNU_MathProg#57]
The check gives a warning/error when a TotalAnnualMinCapacityInvestment is defined for a technology but TotalAnnualMaxCapacityInvestment is not defined. 
The issue is probably that the default value is -1.
However, the modeller might simply not think of putting a TotalAnnualMaxCapacityInvestment since it is perhaps not needed.

**Comment by vignesh1987** [comment]
Thanks @HauHe . Yes, the check statement should actually not perform the check if the defaults are used. Thanks for pointing this out.  Will submit a corrected statement
