### ISSUE TITLE
Technology specific discount factor does not work

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS_GNU_MathProg#61]
The current implementation of the technology specific discount factor does not work as expected:

> Unless I am misreading the code, this [technology specific discount rate] is done more or less the same way as it was in the earlier versions of OSeMOSYS (pre 2013 or thereabouts), which doesn’t work because it just discounts every cost element at the new rate. You still need to have a common rate of time preference for the temporal discounting (otherwise a technology with a high discount rate will get comparatively cheaper  the further into the future you get). If you want to introduce technology specific discount rates you need to go through the route of annualizing the capital costs first (at the technology specific discount rate) and then include the annualized capital cost in the objective function, which is then discounted at the global discount rate.

- [ ] Implement annualizing the capital costs first (at the technology specific discount rate)
- [ ] Add global discount rate parameter
- [ ] Include the annualized capital cost in the objective function, which is discounted at the global discount rate

**Comment by tniet** [comment]
One other piece that we might want to consider when implementing this is the build time and costs associated with that.  I recall a spreadsheet that changes overnight costs into financed costs based on build times, but I can't find it right now.  This might be a place where tech specific discount rates apply as well?  @abhishek0208?

**Comment by willu47** [comment]
Closed by #65
