### ISSUE TITLE
Upload model pre-processing script

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS_GNU_MathProg#7]
@abhishek0208 - are you able to share the pre-processing script for reducing the matrix size and thus time for generating the LP matrix with glpsol?

**Comment by abhishek0208** [comment]
It's on my to-do list, @willu47 . The script is ready to go up but I'd like to include a Readme when putting it up.

**Comment by willu47** [comment]
Closed by #20
