### ISSUE TITLE
Archiving OSeMOSYS

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/OSeMOSYS_GNU_MathProg#92]
I was wondering if we should archive the OSeMOSYS code in Zenodo. 
Right now we have a citation file in the repo asking the user to reference the 2011 OSeMOSYS paper.
But an archive on Zenodo would allow to specifically point to the version of OSeMOSYS used with a DOI.
I see that pyPSA has archived it's GitHub repo whereas Calliope hasn't.

**Comment by willu47** [comment]
Good idea @HauHe.  The steps should be:

- change the current citation.md file to a citation.cff file, following the instructions provided [here](https://citation-file-format.github.io/)
- Create a link to Zenodo follow [these instructions](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) (an admin e.g. @willu47 should do this)
- Potentially also write a `.zenodo.json` file, although I believe Zenodo should also pick up the `.cff` file
- Add a workflow [as we have done for otoole](https://github.com/OSeMOSYS/otoole/blob/master/.github/workflows/citation.yaml) to automatically check the citation file format and syntax.
